Jupyter Extension Version: 2021.11.1001550889.
Python Extension Verison: 2021.12.1559732655.
Info 17:48:20: Experimentation service retrieved: [object Object]
Info 17:48:20: ZMQ install verified.
Error 17:48:21: Jupyter Extension (Error in Failed to update settings.json, method:fixSettingsFile): [EntryNotFound (FileSystemError): Unable to read file '/home/shaurya/.config/Code/User/settings.json' (Error: Unable to resolve nonexistent file '/home/shaurya/.config/Code/User/settings.json')
	at Function._handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:84547)
	at Object.readFile (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:83461)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async m.readFile (/home/shaurya/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:104:380788)
	at async g.fixSettingsFile (/home/shaurya/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:537959)
	at async Promise.all (index 0)
	at async g.updateSettings (/home/shaurya/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:539709)] {
  code: 'FileNotFound'
}
Error 17:48:21: Jupyter Extension (Error in Failed to update settings.json, method:fixSettingsFile): [EntryNotFound (FileSystemError): Unable to read file '/home/shaurya/Documents/devkit/.vscode/settings.json' (Error: Unable to resolve nonexistent file '/home/shaurya/Documents/devkit/.vscode/settings.json')
	at Function._handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:84547)
	at Object.readFile (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:83461)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async m.readFile (/home/shaurya/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:104:380788)
	at async g.fixSettingsFile (/home/shaurya/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:537959)
	at async Promise.all (index 1)
	at async g.updateSettings (/home/shaurya/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:539709)] {
  code: 'FileNotFound'
}
Info 17:48:21: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 17:48:22: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
Info 17:48:22: Process Execution: > /bin/python3 -c "import pip"
> /bin/python3 -c "import pip"
Info 18:32:03: Shutting down notebooks for 2f296f63-fd0b-496d-80dc-63a7bacd7219
Info 18:32:03: Disposing HostJupyterExecution 9297a04c-8402-4563-83db-10a1c2a45dc9
Info 18:32:03: Disposing super HostJupyterExecution 9297a04c-8402-4563-83db-10a1c2a45dc9
Info 18:32:03: Disposing HostJupyterExecution 9297a04c-8402-4563-83db-10a1c2a45dc9
Info 18:32:03: Finished disposing HostJupyterExecution  9297a04c-8402-4563-83db-10a1c2a45dc9
Info 18:32:03: Cleaning up server cache 9297a04c-8402-4563-83db-10a1c2a45dc9
Info 18:32:03: Finished disposing HostJupyterExecution  9297a04c-8402-4563-83db-10a1c2a45dc9
